# This is a basic workflow to help you get started with Actions

name: My-FirstGitHubActions


on:
  push:
   branches: 
          - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my-testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Helo Message
        run: echo "Hello World from my testing"
        
  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    
    steps:
      - name: Print Helo Message
        run: echo "Hello World from my deploy"
      - name: Start few command
        run: |
          echo "Hello World one"
          echo "Hello World two"
          echo "Hello World three"
        
  my-second-deploy:
    runs-on: ubuntu-latest
    needs: [my-deploy]
    
    steps:
      - name: Print Helo Message
        run: echo "Second"

