# This is a basic workflow to help you get started with Actions

name: My-FirstGitHubActions


on:
  push:
   branches: 
          - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my-testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Helo Message
        run: echo "Hello World from my testing" / echo "Hello World"
